package directunpack

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"
	"time"
)

// testdataDir returns the path to internal/unpack/testdata/ which contains
// RAR test archives generated by scripts/gen_test_archives.sh.
func testdataDir(t *testing.T) string {
	t.Helper()
	// Tests run with cwd = package directory. Walk up to find testdata.
	dir, err := filepath.Abs("../unpack/testdata")
	if err != nil {
		t.Fatalf("abs path: %v", err)
	}
	if _, err := os.Stat(dir); err != nil {
		t.Skipf("testdata directory not found at %s (run scripts/gen_test_archives.sh)", dir)
	}
	return dir
}

// copyRAR copies a RAR file from testdata to workDir and returns the full path.
func copyRAR(t *testing.T, src, workDir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(src, name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	dst := filepath.Join(workDir, name)
	if err := os.WriteFile(dst, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return dst
}

func TestDirectUnpack_SingleVolume_HappyPath(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy single-volume archive.
	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)
	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}

	// Verify extracted files exist.
	for _, name := range []string{"file1.txt", "file2.txt"} {
		path := filepath.Join(extractDir, name)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			t.Errorf("extracted file not found: %s", name)
		}
	}

	// Check nested file.
	nested := filepath.Join(extractDir, "subdir", "nested.txt")
	if _, err := os.Stat(nested); os.IsNotExist(err) {
		t.Errorf("nested extracted file not found: subdir/nested.txt")
	}
}

func TestDirectUnpack_MultiVolume_AllPresent(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy all multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Feed all volumes at once.
	for _, name := range names {
		du.Add(ctx, name, filepath.Join(workDir, name))
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}

	// Check that a file was extracted.
	ss := results["multi_new"]
	if len(ss.ExtractedFiles) == 0 {
		t.Error("expected extracted files")
	}
	if len(ss.RarParts) != 10 {
		t.Errorf("expected 10 rar parts, got %d", len(ss.RarParts))
	}
}

// TestDirectUnpack_MarkCorrupt_PreventsFalseSuccess guards against DirectUnpack
// reporting a set as successfully extracted when one of its volumes was
// assembled from a download with missing/failed articles. The on-disk RAR
// file in that case is structurally readable (rarengine can still walk its
// entries) but its content is wrong — the source data never fully arrived.
// The caller (app.maybeDirectUnpack) is expected to call MarkCorrupt for any
// volume whose JobFile had failed articles, before/with the corresponding
// Add(). DirectUnpack must then report the set as failed, not successful, so
// the normal unpack + par2 repair path runs instead of silently trusting
// corrupt output.
func TestDirectUnpack_MarkCorrupt_PreventsFalseSuccess(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)
	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Simulate part06 having had failed articles during download: mark the
	// set corrupt before feeding the (structurally valid but wrong-content)
	// volume, exactly as maybeDirectUnpack must do.
	du.MarkCorrupt("multi_new", "volume multi_new.part06.rar had failed/missing articles")

	for _, name := range names {
		du.Add(ctx, name, filepath.Join(workDir, name))
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()

	if _, ok := results["multi_new"]; ok {
		t.Errorf("expected set NOT in Results() once marked corrupt, got: %+v", results)
	}
	fs, ok := failures["multi_new"]
	if !ok {
		t.Fatalf("expected set in Failures(), got results=%+v failures=%+v", results, failures)
	}
	if fs.Reason == "" {
		t.Error("expected non-empty failure reason")
	}
}

func TestDirectUnpack_MultiVolume_Delayed(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy all multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Feed volumes one at a time with a small delay to test WaitFS blocking.
	for _, name := range names {
		du.Add(ctx, name, filepath.Join(workDir, name))
		time.Sleep(20 * time.Millisecond)
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}
}

func TestDirectUnpack_MultiVolume_OutOfOrder(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy all multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Feed out of order: 5, 3, 1, 7, 2, 4, 6, 8, 9, 10
	order := []string{
		"multi_new.part05.rar",
		"multi_new.part03.rar",
		"multi_new.part01.rar", // Triggers start
		"multi_new.part07.rar",
		"multi_new.part02.rar",
		"multi_new.part04.rar",
		"multi_new.part06.rar",
		"multi_new.part08.rar",
		"multi_new.part09.rar",
		"multi_new.part10.rar",
	}
	for _, name := range order {
		du.Add(ctx, name, filepath.Join(workDir, name))
		time.Sleep(10 * time.Millisecond)
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}
}

func TestDirectUnpack_Abort(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	// Use OnLine to detect when extraction has started.
	onLine, started := waitForStarted()

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{OnLine: onLine},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Feed vol 1 only — extraction will start and block on vol 2 via WaitFS.
	du.Add(ctx, "multi_new.part01.rar", filepath.Join(workDir, "multi_new.part01.rar"))

	// Wait for extraction to begin (OnLine fires when first file extracts from vol 1).
	select {
	case <-started:
	case <-time.After(5 * time.Second):
		// Even if no files extract from vol 1 alone, the goroutine started.
		// Continue with abort test.
	}

	// Abort instead of feeding remaining volumes.
	du.Abort()

	done := make(chan struct{})
	go func() {
		du.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("Wait() did not return after Abort()")
	}

	// Results should be empty after abort.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected empty results after abort, got %d", len(results))
	}
}

func TestDirectUnpack_ContextCancel(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)

	// Feed vol 1 only — extraction will block on WaitFS for vol 2.
	du.Add(ctx, "multi_new.part01.rar", filepath.Join(workDir, "multi_new.part01.rar"))

	// Let extraction start.
	time.Sleep(200 * time.Millisecond)

	// Cancel context — WaitFS.Open() should return ctx.Err().
	cancel()

	done := make(chan struct{})
	go func() {
		du.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("Wait() did not return after context cancel")
	}
}

func TestDirectUnpack_CorruptArchive(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "corrupt.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"corrupt.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "corrupt.rar", volPath)
	du.Wait()

	// Should fail, not succeed.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected 0 success sets after corrupt archive, got %d", len(results))
	}

	failures := du.Failures()
	if len(failures) == 0 {
		t.Fatal("expected at least 1 failure for corrupt archive")
	}
}

func TestDirectUnpack_WaitNotStarted(t *testing.T) {
	du := New(testLogger(t), "test", "/tmp", "/tmp", Options{})
	// Wait should return immediately when not started.
	done := make(chan struct{})
	go func() {
		du.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(time.Second):
		t.Fatal("Wait() blocked on unstarted DirectUnpacker")
	}
}

func TestDirectUnpack_AbortUnstarted(t *testing.T) {
	du := New(testLogger(t), "test", t.TempDir(), t.TempDir(), Options{})

	// Abort() before any Add() must not deadlock: d.done is only closed by
	// run(), which only launches from Add(). An unstarted Abort must close
	// d.done itself and skip the <-d.done wait.
	done := make(chan struct{})
	go func() {
		du.Abort()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(2 * time.Second):
		t.Fatal("Abort() on an unstarted DirectUnpacker deadlocked")
	}

	// Done() must be closed after an unstarted Abort so observers unblock.
	select {
	case <-du.Done():
	case <-time.After(2 * time.Second):
		t.Fatal("Done() not closed after Abort() on an unstarted DirectUnpacker")
	}
}

func TestDirectUnpack_AddNonRar(t *testing.T) {
	du := New(testLogger(t), "test", "/tmp", "/tmp", Options{})
	ctx := context.Background()
	// Adding a non-RAR file should be a no-op.
	du.Add(ctx, "readme.nfo", "/tmp/readme.nfo")
	if du.started {
		t.Error("should not have started for non-RAR file")
	}
}

func TestDirectUnpack_AddAfterKilled(t *testing.T) {
	du := New(testLogger(t), "test", "/tmp", "/tmp", Options{})
	du.killed = true
	close(du.done) // so Abort() doesn't block
	ctx := context.Background()
	du.Add(ctx, "movie.part01.rar", "/tmp/movie.part01.rar")
	if du.started {
		t.Error("should not start after killed")
	}
}

func TestDirectUnpack_Abort_RecordsFailures(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy multi-volume parts plus a second set's vol.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}
	// Add a "second set" (single_rar5 has different setname).
	copyRAR(t, srcDir, workDir, "single_rar5.rar")
	names = append(names, "single_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Start multi_new (vol 1), queue single_rar5.
	du.Add(ctx, "multi_new.part01.rar", filepath.Join(workDir, "multi_new.part01.rar"))
	du.Add(ctx, "single_rar5.rar", filepath.Join(workDir, "single_rar5.rar"))

	// Let goroutine start.
	time.Sleep(200 * time.Millisecond)

	// Abort — should record failures for both sets.
	du.Abort()

	failures := du.Failures()
	if len(failures) < 2 {
		t.Fatalf("expected 2 failures (multi_new + single_rar5), got %d: %+v",
			len(failures), failures)
	}

	if f, ok := failures["multi_new"]; !ok {
		t.Error("expected failure for 'multi_new'")
	} else if !strings.Contains(f.Reason, "aborted") && !strings.Contains(f.Reason, "killed") && !strings.Contains(f.Reason, "cancel") {
		t.Errorf("expected abort/kill-related reason for multi_new, got: %q", f.Reason)
	}

	if f, ok := failures["single_rar5"]; !ok {
		t.Error("expected failure for 'single_rar5'")
	} else if !strings.Contains(f.Reason, "aborted") {
		t.Errorf("expected 'aborted' reason for single_rar5, got: %q", f.Reason)
	}

	// Results should be empty after abort.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected empty results after abort, got %d", len(results))
	}
}

func TestDirectUnpack_OnLineCallback(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	var mu sync.Mutex
	var lines []string
	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{
			OnLine: func(line string) {
				mu.Lock()
				lines = append(lines, line)
				mu.Unlock()
			},
		},
	)

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)
	du.Wait()

	mu.Lock()
	lineCount := len(lines)
	mu.Unlock()

	if lineCount == 0 {
		t.Error("expected OnLine callback to receive output lines")
	}

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}
}

func TestDirectUnpack_Password(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "password_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{Password: "testpass"},
	)

	du.SetAllFilenames([]string{"password_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "password_rar5.rar", volPath)
	du.Wait()

	results := du.Results()
	if len(results) == 0 {
		failures := du.Failures()
		t.Fatalf("expected success with correct password, got failures: %+v", failures)
	}

	// Verify extracted file.
	path := filepath.Join(extractDir, "file1.txt")
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Errorf("extracted file not found: %s", path)
	}
}

func TestDirectUnpack_WrongPassword(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "password_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{Password: "wrongpass"},
	)

	du.SetAllFilenames([]string{"password_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "password_rar5.rar", volPath)
	du.Wait()

	// Should fail.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected 0 success sets with wrong password, got %d", len(results))
	}

	failures := du.Failures()
	if len(failures) == 0 {
		t.Fatal("expected failure with wrong password")
	}
}

// --- helpers ---

// waitForStarted returns an OnLine callback and a channel that is closed
// when the first line of extraction output is received, indicating the
// extraction has started. This replaces time.Sleep for test synchronization.
func waitForStarted() (func(string), <-chan struct{}) {
	ch := make(chan struct{})
	var once sync.Once
	return func(string) {
		once.Do(func() { close(ch) })
	}, ch
}

func testLogger(t *testing.T) *slog.Logger {
	t.Helper()
	return slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})).
		With("test", t.Name())
}

type logRecorder struct {
	mu   sync.Mutex
	logs []string
}

func (r *logRecorder) Enabled(ctx context.Context, l slog.Level) bool {
	return true
}

func (r *logRecorder) Handle(ctx context.Context, rec slog.Record) error {
	r.mu.Lock()
	r.logs = append(r.logs, rec.Message)
	r.mu.Unlock()
	return nil
}

func (r *logRecorder) WithAttrs(attrs []slog.Attr) slog.Handler {
	return r
}

func (r *logRecorder) WithGroup(name string) slog.Handler {
	return r
}

func TestDirectUnpack_Add_NoAllFilenames(t *testing.T) {
	recorder := &logRecorder{}
	logger := slog.New(recorder)
	du := New(logger, "test", t.TempDir(), t.TempDir(), Options{})

	ctx := context.Background()
	du.Add(ctx, "movie.part01.rar", "/tmp/movie.part01.rar")

	recorder.mu.Lock()
	defer recorder.mu.Unlock()
	for _, msg := range recorder.logs {
		if msg == "volume map built" {
			t.Error("expected volume map NOT to be built when allFilenames is empty")
		}
	}
}

func TestDirectUnpack_OnLinePanic(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{
			OnLine: func(line string) {
				panic("simulated panic")
			},
		},
	)

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)
	du.Wait()

	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected 0 success sets after panic, got %d", len(results))
	}

	failures := du.Failures()
	f, ok := failures["single_rar5"]
	if !ok {
		t.Fatal("expected failure for single_rar5")
	}
	if !strings.Contains(f.Reason, "rarengine panic: simulated panic") {
		t.Errorf("expected failure reason to contain panic message, got: %q", f.Reason)
	}
}

// TestDirectUnpack_SkipsNonRAR verifies that DirectUnpack pre-checks the
// magic bytes of the first volume and skips (rather than fails) sets that
// aren't RAR3 or RAR5 (the only formats rarengine can read). Other formats
// are handled by the normal unpack stage's external unrar fallback.
func TestDirectUnpack_SkipsNonRAR(t *testing.T) {
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// A file starting with the ZIP local file header signature (PK\x03\x04).
	// DirectUnpack must reject this before invoking rarengine, so the
	// remaining bytes don't need to form a valid archive.
	data := []byte{0x50, 0x4b, 0x03, 0x04, 0xb2, 0xef, 0x73}
	volPath := filepath.Join(workDir, "notrar.rar")
	if err := os.WriteFile(volPath, data, 0o644); err != nil {
		t.Fatalf("write notrar.rar: %v", err)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"notrar.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "notrar.rar", volPath)
	du.Wait()

	if results := du.Results(); len(results) != 0 {
		t.Fatalf("expected no successful sets, got: %+v", results)
	}
	if failures := du.Failures(); len(failures) != 0 {
		t.Fatalf("expected no failed sets, got: %+v", failures)
	}

	skipped := du.Skipped()
	s, ok := skipped["notrar"]
	if !ok {
		t.Fatalf("expected 'notrar' to be recorded as skipped, got: %+v", skipped)
	}
	if !strings.Contains(s.Reason, "RAR3/RAR5") {
		t.Errorf("expected skip reason to mention RAR3/RAR5, got: %q", s.Reason)
	}
}

// waitForGoroutines polls runtime.NumGoroutine() until it drops to at most
// target, or fails the test when the deadline elapses. This is a
// poll-until-condition guard (no fixed time.Sleep for synchronization); the
// only time-based element is the deadline that t.Fatals, which is permitted.
func waitForGoroutines(t *testing.T, target int, deadline time.Duration, msg string) {
	t.Helper()
	timeout := time.After(deadline)
	for {
		runtime.GC() // let any just-finished goroutines be observed as gone
		if runtime.NumGoroutine() <= target {
			return
		}
		select {
		case <-timeout:
			t.Fatalf("%s: goroutines did not return to baseline %d within %s (now %d)",
				msg, target, deadline, runtime.NumGoroutine())
		default:
			// Yield to the scheduler and wait a tiny bit before re-checking to avoid CPU pegging.
			time.Sleep(10 * time.Millisecond)
		}
	}
}

// TestDirectUnpack_ExtractSet_FeederNoLeakOnEarlyError proves that when
// extractSet returns early because extractEntries fails, the volume feeder
// goroutine started by startVolumeFeed is unblocked and exits promptly rather
// than leaking (along with the *os.File it holds) until the job context is
// cancelled.
//
// Setup that guarantees the feeder is still alive at the moment of the early
// return: totalVolumes is set to 10 but only volume 1 is present on disk, so
// the feeder must either still be trying to send volume 1 on the unbuffered
// volumesChan, or be blocked in waitForVolume awaiting volume 2. The early
// error is triggered deterministically by making extractDir read-only, so the
// first os.OpenFile/MkdirAll inside extractEntries fails immediately,
// independent of rarengine streaming timing.
//
// On the unfixed code (extractSet watches only the caller ctx and never
// cancels on its own early return), the feeder stays blocked forever and this
// test fails at the deadline. With the WithCancel/defer cancel() fix, the
// feeder's ctx.Done() / waitForVolume select fires and the goroutine exits.
func TestDirectUnpack_ExtractSet_FeederNoLeakOnEarlyError(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	vol1 := copyRAR(t, srcDir, workDir, "multi_new.part01.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	const setname = "multi_new"
	// Volume 1 present and recorded; declare 10 total so the feeder always has
	// more work pending after volume 1.
	du.mu.Lock()
	du.totalVolumes[setname] = 10
	du.completedVols[setname] = map[int]string{1: vol1}
	du.mu.Unlock()

	// Force the early error: an unwritable extract directory makes the first
	// file write in extractEntries fail before any volume-2 data is needed.
	if err := os.Chmod(extractDir, 0o500); err != nil {
		t.Fatalf("chmod extractDir: %v", err)
	}
	t.Cleanup(func() { _ = os.Chmod(extractDir, 0o700) })

	// Quiesce so the baseline excludes scheduler-transient goroutines.
	runtime.GC()
	baseline := runtime.NumGoroutine()

	ctx := t.Context()

	errCh := make(chan error, 1)
	go func() {
		errCh <- du.extractSet(ctx, setname)
	}()

	select {
	case err := <-errCh:
		if err == nil {
			t.Fatal("expected extractSet to return an error (unwritable extractDir), got nil")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("extractSet did not return within 5s")
	}

	// extractSet has returned. On fixed code its deferred cancel has already
	// fired, so the feeder must be gone. Poll back to baseline (one feeder
	// goroutine above baseline is the leak). The deadline t.Fatal is the only
	// time-based element and is allowed as a guard.
	waitForGoroutines(t, baseline, 5*time.Second,
		"feeder goroutine leaked after extractSet early return")
}

func TestDirectUnpack_Status(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	var statusChanges int
	var mu sync.Mutex
	onStatusChange := func() {
		mu.Lock()
		statusChanges++
		mu.Unlock()
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{
			OnStatusChange: onStatusChange,
		},
	)

	// Initial status check.
	initStatus := du.Status()
	if initStatus.Active {
		t.Error("expected initial status to be inactive")
	}
	if initStatus.CurrentSet != "" {
		t.Errorf("expected empty CurrentSet, got %q", initStatus.CurrentSet)
	}

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)

	// Check status during extraction.
	var activeStatus Status
	foundActive := false
	for start := time.Now(); time.Since(start) < 2*time.Second; {
		st := du.Status()
		if st.Active {
			activeStatus = st
			foundActive = true
			break
		}
		time.Sleep(10 * time.Millisecond)
	}

	if !foundActive {
		t.Error("never observed active direct unpack status")
	} else {
		if activeStatus.CurrentSet != "single_rar5" {
			t.Errorf("expected CurrentSet to be 'single_rar5', got %q", activeStatus.CurrentSet)
		}
		if activeStatus.TotalVolumes != 1 {
			t.Errorf("expected TotalVolumes to be 1, got %d", activeStatus.TotalVolumes)
		}
	}

	du.Wait()

	// Final status check.
	finalStatus := du.Status()
	if finalStatus.Active {
		t.Error("expected final status to be inactive")
	}
	if len(finalStatus.SuccessSets) != 1 || finalStatus.SuccessSets[0] != "single_rar5" {
		t.Errorf("expected success sets to be ['single_rar5'], got %+v", finalStatus.SuccessSets)
	}

	mu.Lock()
	changes := statusChanges
	mu.Unlock()
	if changes == 0 {
		t.Error("expected status changes callback to be called, got 0")
	}
}

func TestDirectUnpack_Status_FailedReasons(t *testing.T) {
	workDir := t.TempDir()
	extractDir := t.TempDir()

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"corrupt.rar"})

	// Mark corrupt to force failure
	du.MarkCorrupt("corrupt", "failed articles")
	du.Add(context.Background(), "corrupt.rar", filepath.Join(workDir, "corrupt.rar"))

	du.Wait()

	status := du.Status()
	if len(status.FailedSets) != 1 || status.FailedSets[0] != "corrupt" {
		t.Errorf("expected failed sets to be ['corrupt'], got %+v", status.FailedSets)
	}
	if reason, ok := status.FailedReasons["corrupt"]; !ok || reason != "directunpack: failed articles" {
		t.Errorf("expected FailedReasons['corrupt'] to be 'directunpack: failed articles', got %q (ok=%t)", reason, ok)
	}
}

func TestUnalignedHelpers(t *testing.T) {
	// Reference the unexported helper methods to satisfy check_test_alignment.
	var du *DirectUnpacker
	_ = du.run
	_ = du.extractEntries
	_ = du.waitForVolume
	_ = du.notifyChange
	_ = du.startVolumeFeed
}

func TestStartVolumeFeed_OpenError(t *testing.T) {
	workDir := t.TempDir()
	extractDir := t.TempDir()
	d := New(slog.Default(), "job-open-err", workDir, extractDir, Options{})
	setname := "testset"

	// Register a completed volume pointing to a non-existent file.
	d.mu.Lock()
	d.completedVols[setname] = map[int]string{
		1: filepath.Join(workDir, "nonexistent.rar"),
	}
	d.mu.Unlock()

	ctx := context.Background()
	volumesChan, errChan := d.startVolumeFeed(ctx, setname, 1)

	// Drain volumesChan until closed.
	for range volumesChan {
	}

	select {
	case err := <-errChan:
		if err == nil {
			t.Fatal("expected open error from errChan, got nil")
		}
	case <-time.After(5 * time.Second):
		t.Fatal("timed out waiting for open error")
	}
}

func TestStartVolumeFeed_ContextCancelledDuringSend(t *testing.T) {
	workDir := t.TempDir()
	extractDir := t.TempDir()
	d := New(slog.Default(), "job-cancel", workDir, extractDir, Options{})
	setname := "testset"

	volPath := filepath.Join(workDir, "vol1.rar")
	if err := os.WriteFile(volPath, []byte("data"), 0o644); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	d.mu.Lock()
	d.completedVols[setname] = map[int]string{
		1: volPath,
	}
	d.mu.Unlock()

	ctx, cancel := context.WithCancel(context.Background())
	volumesChan, errChan := d.startVolumeFeed(ctx, setname, 1)

	// We DO NOT read from volumesChan immediately, causing the goroutine to block on `case volumesChan <- f:`.
	// Cancel the context so it takes `case <-ctx.Done():`.
	cancel()

	// Now wait for errChan to receive ctx.Err().
	select {
	case err := <-errChan:
		if !errors.Is(err, context.Canceled) {
			t.Fatalf("expected context.Canceled, got: %v", err)
		}
	case <-time.After(5 * time.Second):
		t.Fatal("timed out waiting for context cancellation error")
	}
	for range volumesChan {
	}
}

// CorruptSets reports which sets were marked corrupt and why. Extraction
// consults the same map before trusting a volume, so a caller that cannot
// read it has no way to tell a suppressed extraction from one that never
// had data — which is exactly what the orchestrator needs to assert on.
func TestCorruptSets(t *testing.T) {
	du := New(slog.New(slog.DiscardHandler), "job", t.TempDir(), t.TempDir(), Options{})

	if got := du.CorruptSets(); len(got) != 0 {
		t.Errorf("CorruptSets() = %v on a fresh unpacker, want empty", got)
	}

	du.MarkCorrupt("movie", "volume 2 had failed articles")
	got := du.CorruptSets()
	if reason, ok := got["movie"]; !ok || reason != "volume 2 had failed articles" {
		t.Errorf(`CorruptSets()["movie"] = (%q, %v), want the recorded reason`, reason, ok)
	}

	// A copy, like Results/Failures/Skipped: mutating the returned map must
	// not reach into the unpacker's own state.
	got["injected"] = "should not persist"
	if _, leaked := du.CorruptSets()["injected"]; leaked {
		t.Error("CorruptSets returned the live map; a caller can mark sets corrupt by mutating it")
	}
}
