package directunpack

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// testdataDir returns the path to internal/unpack/testdata/ which contains
// RAR test archives generated by scripts/gen_test_archives.sh.
func testdataDir(t *testing.T) string {
	t.Helper()
	// Tests run with cwd = package directory. Walk up to find testdata.
	dir, err := filepath.Abs("../unpack/testdata")
	if err != nil {
		t.Fatalf("abs path: %v", err)
	}
	if _, err := os.Stat(dir); err != nil {
		t.Skipf("testdata directory not found at %s (run scripts/gen_test_archives.sh)", dir)
	}
	return dir
}

// copyRAR copies a RAR file from testdata to workDir and returns the full path.
func copyRAR(t *testing.T, src, workDir, name string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(src, name))
	if err != nil {
		t.Fatalf("read %s: %v", name, err)
	}
	dst := filepath.Join(workDir, name)
	if err := os.WriteFile(dst, data, 0o644); err != nil {
		t.Fatalf("write %s: %v", name, err)
	}
	return dst
}

func TestDirectUnpack_SingleVolume_HappyPath(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy single-volume archive.
	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)
	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}

	// Verify extracted files exist.
	for _, name := range []string{"file1.txt", "file2.txt"} {
		path := filepath.Join(extractDir, name)
		if _, err := os.Stat(path); os.IsNotExist(err) {
			t.Errorf("extracted file not found: %s", name)
		}
	}

	// Check nested file.
	nested := filepath.Join(extractDir, "subdir", "nested.txt")
	if _, err := os.Stat(nested); os.IsNotExist(err) {
		t.Errorf("nested extracted file not found: subdir/nested.txt")
	}
}

func TestDirectUnpack_MultiVolume_AllPresent(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy all multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Feed all volumes at once.
	for _, name := range names {
		du.Add(ctx, name, filepath.Join(workDir, name))
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}

	// Check that a file was extracted.
	ss := results["multi_new"]
	if len(ss.ExtractedFiles) == 0 {
		t.Error("expected extracted files")
	}
	if len(ss.RarParts) != 10 {
		t.Errorf("expected 10 rar parts, got %d", len(ss.RarParts))
	}
}

func TestDirectUnpack_MultiVolume_Delayed(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy all multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Feed volumes one at a time with a small delay to test WaitFS blocking.
	for _, name := range names {
		du.Add(ctx, name, filepath.Join(workDir, name))
		time.Sleep(20 * time.Millisecond)
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}
}

func TestDirectUnpack_MultiVolume_OutOfOrder(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy all multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 15*time.Second)
	defer cancel()

	// Feed out of order: 5, 3, 1, 7, 2, 4, 6, 8, 9, 10
	order := []string{
		"multi_new.part05.rar",
		"multi_new.part03.rar",
		"multi_new.part01.rar", // Triggers start
		"multi_new.part07.rar",
		"multi_new.part02.rar",
		"multi_new.part04.rar",
		"multi_new.part06.rar",
		"multi_new.part08.rar",
		"multi_new.part09.rar",
		"multi_new.part10.rar",
	}
	for _, name := range order {
		du.Add(ctx, name, filepath.Join(workDir, name))
		time.Sleep(10 * time.Millisecond)
	}

	du.Wait()

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}
}

func TestDirectUnpack_Abort(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy multi-volume parts.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	// Use OnLine to detect when extraction has started.
	onLine, started := waitForStarted()

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{OnLine: onLine},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Feed vol 1 only — extraction will start and block on vol 2 via WaitFS.
	du.Add(ctx, "multi_new.part01.rar", filepath.Join(workDir, "multi_new.part01.rar"))

	// Wait for extraction to begin (OnLine fires when first file extracts from vol 1).
	select {
	case <-started:
	case <-time.After(5 * time.Second):
		// Even if no files extract from vol 1 alone, the goroutine started.
		// Continue with abort test.
	}

	// Abort instead of feeding remaining volumes.
	du.Abort()

	done := make(chan struct{})
	go func() {
		du.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("Wait() did not return after Abort()")
	}

	// Results should be empty after abort.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected empty results after abort, got %d", len(results))
	}
}

func TestDirectUnpack_ContextCancel(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)

	// Feed vol 1 only — extraction will block on WaitFS for vol 2.
	du.Add(ctx, "multi_new.part01.rar", filepath.Join(workDir, "multi_new.part01.rar"))

	// Let extraction start.
	time.Sleep(200 * time.Millisecond)

	// Cancel context — WaitFS.Open() should return ctx.Err().
	cancel()

	done := make(chan struct{})
	go func() {
		du.Wait()
		close(done)
	}()

	select {
	case <-done:
	case <-time.After(5 * time.Second):
		t.Fatal("Wait() did not return after context cancel")
	}
}

func TestDirectUnpack_CorruptArchive(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "corrupt.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"corrupt.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "corrupt.rar", volPath)
	du.Wait()

	// Should fail, not succeed.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected 0 success sets after corrupt archive, got %d", len(results))
	}

	failures := du.Failures()
	if len(failures) == 0 {
		t.Fatal("expected at least 1 failure for corrupt archive")
	}
}

func TestDirectUnpack_WaitNotStarted(t *testing.T) {
	du := New(testLogger(t), "test", "/tmp", "/tmp", Options{})
	// Wait should return immediately when not started.
	done := make(chan struct{})
	go func() {
		du.Wait()
		close(done)
	}()
	select {
	case <-done:
	case <-time.After(time.Second):
		t.Fatal("Wait() blocked on unstarted DirectUnpacker")
	}
}

func TestDirectUnpack_AddNonRar(t *testing.T) {
	du := New(testLogger(t), "test", "/tmp", "/tmp", Options{})
	ctx := context.Background()
	// Adding a non-RAR file should be a no-op.
	du.Add(ctx, "readme.nfo", "/tmp/readme.nfo")
	if du.started {
		t.Error("should not have started for non-RAR file")
	}
}

func TestDirectUnpack_AddAfterKilled(t *testing.T) {
	du := New(testLogger(t), "test", "/tmp", "/tmp", Options{})
	du.killed = true
	close(du.done) // so Abort() doesn't block
	ctx := context.Background()
	du.Add(ctx, "movie.part01.rar", "/tmp/movie.part01.rar")
	if du.started {
		t.Error("should not start after killed")
	}
}

func TestDirectUnpack_Abort_RecordsFailures(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// Copy multi-volume parts plus a second set's vol.
	var names []string
	for i := 1; i <= 10; i++ {
		name := fmt.Sprintf("multi_new.part%02d.rar", i)
		copyRAR(t, srcDir, workDir, name)
		names = append(names, name)
	}
	// Add a "second set" (single_rar5 has different setname).
	copyRAR(t, srcDir, workDir, "single_rar5.rar")
	names = append(names, "single_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames(names)

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Start multi_new (vol 1), queue single_rar5.
	du.Add(ctx, "multi_new.part01.rar", filepath.Join(workDir, "multi_new.part01.rar"))
	du.Add(ctx, "single_rar5.rar", filepath.Join(workDir, "single_rar5.rar"))

	// Let goroutine start.
	time.Sleep(200 * time.Millisecond)

	// Abort — should record failures for both sets.
	du.Abort()

	failures := du.Failures()
	if len(failures) < 2 {
		t.Fatalf("expected 2 failures (multi_new + single_rar5), got %d: %+v",
			len(failures), failures)
	}

	if f, ok := failures["multi_new"]; !ok {
		t.Error("expected failure for 'multi_new'")
	} else if !strings.Contains(f.Reason, "aborted") && !strings.Contains(f.Reason, "killed") && !strings.Contains(f.Reason, "cancel") {
		t.Errorf("expected abort/kill-related reason for multi_new, got: %q", f.Reason)
	}

	if f, ok := failures["single_rar5"]; !ok {
		t.Error("expected failure for 'single_rar5'")
	} else if !strings.Contains(f.Reason, "aborted") {
		t.Errorf("expected 'aborted' reason for single_rar5, got: %q", f.Reason)
	}

	// Results should be empty after abort.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected empty results after abort, got %d", len(results))
	}
}

func TestDirectUnpack_OnLineCallback(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	var mu sync.Mutex
	var lines []string
	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{
			OnLine: func(line string) {
				mu.Lock()
				lines = append(lines, line)
				mu.Unlock()
			},
		},
	)

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)
	du.Wait()

	mu.Lock()
	lineCount := len(lines)
	mu.Unlock()

	if lineCount == 0 {
		t.Error("expected OnLine callback to receive output lines")
	}

	results := du.Results()
	failures := du.Failures()
	if len(failures) != 0 {
		t.Fatalf("expected no failures, got: %+v", failures)
	}
	if len(results) == 0 {
		t.Fatal("expected success, got 0 results")
	}
}

func TestDirectUnpack_Password(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "password_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{Password: "testpass"},
	)

	du.SetAllFilenames([]string{"password_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "password_rar5.rar", volPath)
	du.Wait()

	results := du.Results()
	if len(results) == 0 {
		failures := du.Failures()
		t.Fatalf("expected success with correct password, got failures: %+v", failures)
	}

	// Verify extracted file.
	path := filepath.Join(extractDir, "file1.txt")
	if _, err := os.Stat(path); os.IsNotExist(err) {
		t.Errorf("extracted file not found: %s", path)
	}
}

func TestDirectUnpack_WrongPassword(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "password_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{Password: "wrongpass"},
	)

	du.SetAllFilenames([]string{"password_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "password_rar5.rar", volPath)
	du.Wait()

	// Should fail.
	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected 0 success sets with wrong password, got %d", len(results))
	}

	failures := du.Failures()
	if len(failures) == 0 {
		t.Fatal("expected failure with wrong password")
	}
}

// --- helpers ---

// waitForStarted returns an OnLine callback and a channel that is closed
// when the first line of extraction output is received, indicating the
// extraction has started. This replaces time.Sleep for test synchronization.
func waitForStarted() (func(string), <-chan struct{}) {
	ch := make(chan struct{})
	var once sync.Once
	return func(string) {
		once.Do(func() { close(ch) })
	}, ch
}

func fmtPart(n int) string {
	return fmt.Sprintf("movie.part%02d.rar", n)
}

func testLogger(t *testing.T) *slog.Logger {
	t.Helper()
	return slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{Level: slog.LevelDebug})).
		With("test", t.Name())
}

type logRecorder struct {
	mu   sync.Mutex
	logs []string
}

func (r *logRecorder) Enabled(ctx context.Context, l slog.Level) bool {
	return true
}

func (r *logRecorder) Handle(ctx context.Context, rec slog.Record) error {
	r.mu.Lock()
	r.logs = append(r.logs, rec.Message)
	r.mu.Unlock()
	return nil
}

func (r *logRecorder) WithAttrs(attrs []slog.Attr) slog.Handler {
	return r
}

func (r *logRecorder) WithGroup(name string) slog.Handler {
	return r
}

func TestDirectUnpack_Add_NoAllFilenames(t *testing.T) {
	recorder := &logRecorder{}
	logger := slog.New(recorder)
	du := New(logger, "test", t.TempDir(), t.TempDir(), Options{})

	ctx := context.Background()
	du.Add(ctx, "movie.part01.rar", "/tmp/movie.part01.rar")

	recorder.mu.Lock()
	defer recorder.mu.Unlock()
	for _, msg := range recorder.logs {
		if msg == "volume map built" {
			t.Error("expected volume map NOT to be built when allFilenames is empty")
		}
	}
}

func TestDirectUnpack_OnLinePanic(t *testing.T) {
	srcDir := testdataDir(t)
	workDir := t.TempDir()
	extractDir := t.TempDir()

	volPath := copyRAR(t, srcDir, workDir, "single_rar5.rar")

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{
			OnLine: func(line string) {
				panic("simulated panic")
			},
		},
	)

	du.SetAllFilenames([]string{"single_rar5.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "single_rar5.rar", volPath)
	du.Wait()

	results := du.Results()
	if len(results) != 0 {
		t.Fatalf("expected 0 success sets after panic, got %d", len(results))
	}

	failures := du.Failures()
	f, ok := failures["single_rar5"]
	if !ok {
		t.Fatal("expected failure for single_rar5")
	}
	if !strings.Contains(f.Reason, "rarengine panic: simulated panic") {
		t.Errorf("expected failure reason to contain panic message, got: %q", f.Reason)
	}
}

// TestDirectUnpack_SkipsNonRAR5 verifies that DirectUnpack pre-checks the
// magic bytes of the first volume and skips (rather than fails) sets that
// aren't RAR5. rarengine only supports RAR5; legacy RAR3/4 archives
// (movie.rar/.r00/.r01/...) are common on Usenet and are handled by the
// normal unpack stage's external unrar fallback.
func TestDirectUnpack_SkipsNonRAR5(t *testing.T) {
	workDir := t.TempDir()
	extractDir := t.TempDir()

	// A minimal file starting with the 7-byte RAR3 magic signature
	// (Rar!\x1a\x07\x00). DirectUnpack must reject this before invoking
	// rarengine, so the remaining bytes don't need to form a valid archive.
	data := []byte{0x52, 0x61, 0x72, 0x21, 0x1a, 0x07, 0x00, 0xb2, 0xef, 0x73}
	volPath := filepath.Join(workDir, "legacy.rar")
	if err := os.WriteFile(volPath, data, 0o644); err != nil {
		t.Fatalf("write legacy.rar: %v", err)
	}

	du := New(
		testLogger(t),
		"test-job",
		workDir,
		extractDir,
		Options{},
	)

	du.SetAllFilenames([]string{"legacy.rar"})

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	du.Add(ctx, "legacy.rar", volPath)
	du.Wait()

	if results := du.Results(); len(results) != 0 {
		t.Fatalf("expected no successful sets, got: %+v", results)
	}
	if failures := du.Failures(); len(failures) != 0 {
		t.Fatalf("expected no failed sets, got: %+v", failures)
	}

	skipped := du.Skipped()
	s, ok := skipped["legacy"]
	if !ok {
		t.Fatalf("expected 'legacy' to be recorded as skipped, got: %+v", skipped)
	}
	if !strings.Contains(s.Reason, "RAR3/4") {
		t.Errorf("expected skip reason to mention RAR3/4, got: %q", s.Reason)
	}
}
